// Type definitions for bq-indicators

export type IndicatorOutput = number[][]; // (number_of_outputs, output_length)
export type IndicatorOptions = (string | number)[];
export type IndicatorType = 'simple' | 'indicator' | 'overlay' | 'math' | 'comparative' | 'unknown';

export type Binding = {
  startByIndex: (index: number, options: IndicatorOptions) => number;
  callByIndex: (index: number, inputs: number[][], options: IndicatorOptions) => IndicatorOutput;
  indicators: Record<keyof Indicators, RawIndicator>;
  version: string;
  path: string;
};

export type RawIndicator = {
  index: number;
  name: string;
  fullName: string;
  type: IndicatorType;
  inputs: number;
  options: number;
  outputs: number;
  inputNames: string[];
  optionNames: string[];
  outputNames: string[];
};

export type Indicator = RawIndicator & {
  indicator: (inputs: number[][], options: IndicatorOptions) => number[][];
  start: (options: IndicatorOptions) => number;
};

export type Indicators = {
  abs: Indicator;
  acos: Indicator;
  ad: Indicator;
  add: Indicator;
  adosc: Indicator;
  adx: Indicator;
  adxr: Indicator;
  andean_osc: Indicator;
  ao: Indicator;
  apo: Indicator;
  aroon: Indicator;
  aroonosc: Indicator;
  asin: Indicator;
  atan: Indicator;
  atr: Indicator;
  avgprice: Indicator;
  bbands: Indicator;
  boom_pro: Indicator;
  bop: Indicator;
  braid_filter: Indicator;
  bq_cvi: Indicator;
  bq_stochrsi: Indicator;
  cci: Indicator;
  ceil: Indicator;
  chaikin_vol: Indicator;
  chandelier_exit: Indicator;
  cm_ema_trendbars: Indicator;
  cmo: Indicator;
  cos: Indicator;
  cosh: Indicator;
  crossany: Indicator;
  crossover: Indicator;
  cvi: Indicator;
  decay: Indicator;
  dema: Indicator;
  di: Indicator;
  di_dx: Indicator;
  div: Indicator;
  dm: Indicator;
  dpo: Indicator;
  dx: Indicator;
  edecay: Indicator;
  ema: Indicator;
  emv: Indicator;
  exp: Indicator;
  floor: Indicator;
  fosc: Indicator;
  ha: Indicator;
  half_trend: Indicator;
  heatmap_vol: Indicator;
  hlc3: Indicator;
  hma: Indicator;
  hull_suite: Indicator;
  insidebar: Indicator;
  kama: Indicator;
  kvo: Indicator;
  lag: Indicator;
  linreg: Indicator;
  linregintercept: Indicator;
  linregslope: Indicator;
  ln: Indicator;
  log10: Indicator;
  macd: Indicator;
  macd_fastline_divergence: Indicator;
  macd_hist_divergence: Indicator;
  marketfi: Indicator;
  mass: Indicator;
  max: Indicator;
  md: Indicator;
  medprice: Indicator;
  mfi: Indicator;
  min: Indicator;
  mobo_band: Indicator;
  mom: Indicator;
  mul: Indicator;
  natr: Indicator;
  price: Indicator;
  psar: Indicator;
  qqe_mod: Indicator;
  roc: Indicator;
  rocr: Indicator;
  round: Indicator;
  rsi: Indicator;
  rsi_divergence: Indicator;
  rvi: Indicator;
  rvi_divergence: Indicator;
  sin: Indicator;
  sinh: Indicator;
  sma: Indicator;
  sqrt: Indicator;
  ssl: Indicator;
  stc: Indicator;
  stddev: Indicator;
  stderr: Indicator;
  stoch: Indicator;
  stoch_divergence: Indicator;
  stoch_rsi: Indicator;
  sub: Indicator;
  sum: Indicator;
  sup_and_res: Indicator;
  supertrend: Indicator;
  tan: Indicator;
  tanh: Indicator;
  tema: Indicator;
  todeg: Indicator;
  torad: Indicator;
  tr: Indicator;
  trima: Indicator;
  trix: Indicator;
  trunc: Indicator;
  tsf: Indicator;
  typprice: Indicator;
  ultosc: Indicator;
  unshift: Indicator;
  ut_bot: Indicator;
  var: Indicator;
  vhf: Indicator;
  volatility: Indicator;
  volatility_oscillator: Indicator;
  vosc: Indicator;
  vu_man_chu_swing: Indicator;
  vwma: Indicator;
  wad: Indicator;
  waddah: Indicator;
  wavetrend: Indicator;
  wcprice: Indicator;
  wilders: Indicator;
  willr: Indicator;
  wma: Indicator;
  zlema: Indicator;
};
